### ISSUE TITLE
Feature request：希望添加色图工具

### ISSUE THREAD

**Issue by meng-luo** [qaralotte/fstring#1]
- 最好分R18和全年龄的
- 最好支持色图信息查询
- 还要rss推送
- 有tg机器人更好

# 作为精神支柱，一定不能少

![58873188](https://user-images.githubusercontent.com/79274361/176861739-b95ea8ac-b976-43ad-bd56-499bb2f0d244.jpg)

**Comment by qaralotte** [comment]
我的建议是[mirai-plugins-pixiv](https://github.com/Nekoer/mirai-plugins-pixiv)
